saucelabs/ci-sauce

src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java

Adding regex replace for access keys. This will stop the access-key from being printed to the console.
https://github.com/saucelabs/ci-sauce/issues/28

Adding regex replace for log output

---

pom.xml

The project uses `com.saucelabs:saucerest` dependency which requires Java 7, so default compilation level should be increased from 6 to 7.

Change source and target compilation levels to Java 7

---

pom.xml
src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java

`org.json:json` and `com.google.code.gson:gson` are competing java libraries for JSON processing. There is no need to have both of them, while only one is enough.

Use org.json:json library for all JSON operations

---

pom.xml

the updated plexus dependencies break the integrations. 
downgrade to fix

downgrade plexus dependencies for teamcity

---

src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java

This was causing an empty string to be added to the command line
arguments, which Sauce Connect 4.6+ treats as an error.

Trim whitespace on options string

---

src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java
src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManagerTest.java

when displaying Sauce Connect Proxy commandline arguments in logs.

[PERF-2686] Cover api key and password with stars

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java

1.
```java
catch (IOException e) {
//thrown if an error occurs starting the process builder
julLogger.log(Level.WARNING, "Exception occurred during invocation of Sauce Connect", e);
throw new SauceConnectException(e);
}
```
is unreachable because previous `catch` block handles all `SauceConnectException`-s and at the same time no `IOException` is thrown in `try` block
2. 
```java
catch (SauceConnectException e) {
throw e;
}
```
doesn't make sense, because it catches the exception and immediately re-throws it

Remove useless catch-throw exception block

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java
src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManagerTest.java

The aim of this PR is to make processing of spaces in SC CLI arguments more user-friendly. SC  fails to start when an empty argument is present:
```
Error: unknown command "" for "sc"
Usage:
sc [flags]
Flags:
-k, --api-key string                Sauce Labs API Key.
-a, --auth strings                  Perform basic authentication when an URL on <host:port> asks for a username and password.
...
```
This PR:
- fixes the processing of duplicate spaces [in `options` string](https://github.com/saucelabs/ci-sauce/blob/cb97b7bc3af822b01676dd65263acd494b1eb851/src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java#L171)
- trims wrapping spaces in [`username` and `apiKey` parameters](https://github.com/saucelabs/ci-sauce/blob/cb97b7bc3af822b01676dd65263acd494b1eb851/src/main/java/co …

Fix handling of spaces in SauceConnect CLI arguments

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java

The removed implementation of `com.saucelabs.ci.sauceconnect.AbstractSauceTunnelManager#generateSauceConnectArgs` generated invalid SauceConnect CLI arguments, since it didn't add flags names for username and API key (-u and -k respectively)

Remove invalid method for SC CLI arguments generation

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java

The removed piece of code is unreachable. `sauceRest` is initialized prior to invocation of `activeTunnelIdentifier` method
https://github.com/saucelabs/ci-sauce/blob/bec624a3f869dbce40ebcb627b3b3e59bc66d249/src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java#L270-L273

Remove unreachable code

---

src/main/java/com/saucelabs/ci/BuildJobInformation.java
src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java

The `os.arch` System property seems to return different things depending on what type of ARM machine is being used.
Right now we only check for `arm` but `aarch` and `amd` are possible as well.
I saw `aarch` when trying to use Jenkin's Docker container.
This meant that SC w/ ARM was not getting installed as this Debian container responded with `aarch64`
Also sneaking in some Javadoc changes that kept me from packaging the jar for testing.
@alexh-sauce setting you as reviewer since it seems you added the ARM functionality. Happy to add someone else though as you don't own this.

Add ARM alternative naming schemes

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
src/test/resources/single_tunnel.json

The `tunnel_identifier` field was mistakenly renamed `tunnel_name` in 8829758bf3b78a6ea27a4176ff5f58cd8014e466. Revert this change, and rename the `activeTunnelName()`  function to `activeTunnelID` to reflect that it returns the tunnel ID, not the tunnel name / identifier.

Fix active tunnel check

---

pom.xml
src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
src/main/java/com/saucelabs/ci/sauceconnect/SauceTunnelManager.java
src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManagerTest.java

The `openConnection()` function didn't take a dataCenter argument, so it never stored that information when the tunnel shuts down later.
This PR adds a new parameter to `openConnection()`, and adds a wrapper function to provide backwards compatibility.

Handle EU datacenter tunnel shutdown

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java

A failure to delete a tunnel shouldn't cause a job to fail - the tunnel will be cleaned up later when idle.

Catch NPE with sauceRest.deleteTunnel()

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java

No need to log into `System.out` once next line of code does logging via JUL which can be confgured to log into various targets including console.

Remove duplicate logging to `System.out`

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java

No point in failing a test if a tunnel fails to delete, as it will be cleaned up eventually on the server side.

Ignore errors on tunnel cleanup

---

pom.xml

`com.saucelabs:saucerest:2.0.3` includes important [fix](https://github.com/saucelabs/saucerest-java/pull/314).

Bump `com.saucelabs:saucerest` from `2.0.2` to `2.0.3`

---

pom.xml
src/main/java/com/saucelabs/ci/BrowserFactory.java
src/main/java/com/saucelabs/ci/SODSeleniumConfiguration.java
src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java

Technically saying `ci-sauce` is a SauceConenct management library (despite its naming). In other words it is not used as a standalone application, it's used as dependency for other libraries/applications/CI_plugins. That's why `ci-sauce` shouldn't have tight coupling with any logging framework (even JDK logger), it should rely on logging facade (SLF4J) instead.

Use logging facade SLF4J instead of JDK Logger

---

pom.xml
src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java
src/test/java/com/saucelabs/sod/ExtractFiles.java

Reasons:
- to reduce memory footprint: `plexus-archiver` is based on  Apache `commons-compress` and includes set of other [dependencies](https://codehaus-plexus.github.io/plexus-archiver/dependencies.html)
- `plexus-archiver` supports [wide range](https://codehaus-plexus.github.io/plexus-archiver/index.html) of archive formats, but they are not needed, as `ci-sauce` works only with 2 formats: `zip` and `tar.gz`
- to optimize performance (less I/O operations):
- `tar`-file is not created anymore while extracting `tar.gz` file
- the archive file is not_downloaded_from_remote-storage/not_extracted_from_jar to the file system, extracting of the archive file is done on the fly

Replace `plexus-archiver` with Apache `commons-compress`

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManagerTest.java

This PR adds wait for tunnel readiness after SauceConnect start.
According to SauceLabs support there could be cases when SauceConnect is started, but tunnel is not yet ready. As the result tests trying to use this tunnel fail. The recommendation was to add check for readiness based on REST API calls.
_What types of changes does your code introduce? Keep the ones that apply:_
_List of tasks you will do to complete the PR_
_List of tasks the reviewer must do to review the PR_
These should highlight any db migrations, feature toggles, etc.

Add tunnel readiness check after SauceConnect start

---

src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManager.java
src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManagerTest.java

Fixes #263 
A few sentences describing the overall goals of the pull request's
commits.
_What types of changes does your code introduce? Keep the ones that apply:_
_List of tasks you will do to complete the PR_
_List of tasks the reviewer must do to review the PR_
These should highlight any db migrations, feature toggles, etc.

Explicitly set execute permission for unpacked SauceConenct binary

---

README.md
pom.xml
src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectManager.java
src/main/resources/download.sh
src/test/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManagerTest.java
src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectManagerTest.java
src/test/java/com/saucelabs/sod/ExtractFiles.java
src/test/resources/started_sc.log
src/test/resources/started_sc_closes.log

Update SC client binaries to Sauce Connect 5
* Update the CLI options.
* Use HTTP API checks instead of parsing log files.
* Bump version to 2.0 as these are breaking API changes, and will also require the user to change their custom CLI options.
Fixes https://github.com/saucelabs/ci-sauce/issues/254

Update to Sauce Connect 5

---

src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectManager.java
src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectManagerTest.java

* Updates to SC client 5.2.2
* Uses the new download endpoint to check versions

Update to SC 5.2.2

---

src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
src/main/java/com/saucelabs/ci/sauceconnect/SauceConnectManager.java
src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectManagerTest.java

Rely on the apiPort value passed as a method parameter instead of class state.
_What types of changes does your code introduce? Keep the ones that apply:_
- Bug fix (non-breaking change which fixes an issue)

Remove apiPort from class state in order to avoid concurrency issues
